### ISSUE TITLE
Demos no funcionan

### ISSUE THREAD

**Issue by nericervin** [codenerix/django-codenerix#41]
python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f1f91ebc0d0>
Traceback (most recent call last):
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/nericervin/Desarrollo2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nericervin/Desarrollo2/django-codenerix-examples/exchange/exchange/urls.py", line 7, in <module>
    from exchange.base import urls as base_urls
  File "/home/nericervin/Desarrollo2/django-codenerix-examples/exchange/exchange/base/urls.py", line 3, in <module>
    from .views import CurrencyList, CurrencyCreate, CurrencyCreateModal, CurrencyUpdate, CurrencyUpdateModal, CurrencyDelete, CurrencyForeign, CurrencyOnline
  File "/home/nericervin/Desarrollo2/django-codenerix-examples/exchange/exchange/base/views.py", line 16, in <module>
    from codenerix.views import GenList, GenCreate, GenCreateModal, GenDetail, GenUpdate, GenUpdateModal, GenDelete, GenForeignKey
  File "/home/nericervin/Desarrollo2/lib/python3.6/site-packages/codenerix/views.py", line 52, in <module>
    from django.utils.translation import string_concat, gettext
ImportError: cannot import name 'string_concat'

**Comment by juanmitaboada** [comment]
Thank you for your advice. The demos has been restored in our latest version. Give it again a try at [django-codenerix-examples](https://github.com/codenerix/django-codenerix-examples)!
